backend:
  repo: renvrant/gatsby-mdx-netlify-cms-starter
  branch: master

media_folder: uploads/img
public_folder: /img

collections:
- name: "mainPages"
  label: "Main Pages and Settings"
  files:
  - file: "src/pages/home.md"
    label: "Home"
    name: "home"
    fields:
    - {
      label: "Template Key",
      name: "templateKey",
      widget: "hidden",
      default: "home-page",
    }
    - { label: Title, name: title, widget: "string" }
    - {
      label: Sections,
      name: sections,
      widget: list,
      fields:
        [
        { label: Title, name: title, widget: string },
        { label: Body, name: body, widget: markdown },
        ]
    }
  - file: "src/pages/config.md"
    label: "Global Settings"
    name: "config"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "hidden-page",
      }
      - { label: Site Title, name: title, widget: "string" }
      - { label: Site Description, name: desc, widget: "string" }
      - { 
          label: Site Menu,
          name: main_nav,
          widget: "relation",
          collection: "content",
          searchFields: ["title"],
          valueField: "title",
          displayFields: ["title"]
        }
      - { label: Twitter Link, name: twitter, widget: "string" }
      - { label: Facebook Link, name: facebook, widget: "string" }
- name: "content"
  label: "Content Pages"
  folder: "src/pages/content"
  create: true
  fields:
  - { label: "Title", name: "title", widget: "string" }
  - { label: "Description", name: "description", widget: "text" }
  - { label: "Body", name: "body", widget: "markdown" }
